### ISSUE TITLE
What is the `name` field in configuration used for?

### ISSUE THREAD

**Issue by dzcpy** [node-casbin/nest-authz#145]
In the documentation there is the following code:
```js
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
  imports: [
    AuthZModule.register({
      model: 'model.conf',
      policy: TypeORMAdapter.newAdapter({
        name: 'casbin',
        type: 'mysql',
        host: 'localhost',
        port: 3306,
        username: 'root',
        password: 'password',
        database: 'nestdb'
      }),
      usernameFromContext: (ctx) => {
        const request = ctx.switchToHttp().getRequest();
        return request.user && request.user.username;
      }
    }),
  ],
})
```
What does the `name` field do in TypeORMAdapter?

**Comment by hsluoyz** [comment]
@Gabriel-403 @Zxilly @nodece

**Comment by nodece** [comment]
The `name` field is the TypeORM instance name.

**Comment by dzcpy** [comment]
@nodece 谢谢解答，不过这个 field 有实际的用处吗？

**Comment by hsluoyz** [comment]
@dzcpy plz use English

**Comment by hsluoyz** [comment]
@dzcpy it's useless and has been removed: https://github.com/node-casbin/nest-authz/commit/bd99591e824fd8c7b0b2c40172361a21fa18aeef

Refer to a better example here: https://github.com/node-casbin/typeorm-adapter#simple-example
