### ISSUE TITLE
does nest-authz works only with typeorm ?

### ISSUE THREAD

**Issue by thorizer** [node-casbin/nest-authz#147]
will nest-authz work with mongoose , typegoose and prisma ? 
casl v5 works only with typeorm in nestjs currently, i'm considering switching to casbin

**Comment by hsluoyz** [comment]
@thorizer you can use other DBs. Change the example to other adapters: https://github.com/node-casbin/nest-authz#initialization

```ts
import { TypeOrmModule } from '@nestjs/typeorm';

@Module({
  imports: [
    AuthZModule.register({
      model: 'model.conf',
      policy: TypeORMAdapter.newAdapter({  // <------------ change here
        name: 'casbin',
        type: 'mysql',
        host: 'localhost',
        port: 3306,
        username: 'root',
        password: 'password',
        database: 'nestdb'
      }),
      usernameFromContext: (ctx) => {
        const request = ctx.switchToHttp().getRequest();
        return request.user && request.user.username;
      }
    }),
  ],
  controllers: [AppController],
  providers: [AppService]
})
```

**Comment by hsluoyz** [comment]
@thorizer `TypeORMAdapter` is just one adapter: https://github.com/node-casbin/typeorm-adapter . You can switch to other Node-Casbin adapters here: https://casbin.org/docs/adapters
