### ISSUE TITLE
v2.5.0 has break changes

### ISSUE THREAD

**Issue by wujingquan** [node-casbin/nest-authz#163]
The AuthZGuard before v2.5.0 expected 3 arguments, but now only expected 1.

**Comment by hsluoyz** [comment]
@wujingquan what's `AuthZGuard`? Can you give more details?

**Comment by wujingquan** [comment]
before v2.5.0 we use the AuthZGuard  as GlobalGuard like  `app.useGlobalGuards(new JwtAuthGuard(reflector), new AuthZGuard(reflector, enforcer, {}));`  but now you take other arguments out，causing code to fail to run.

**Comment by wujingquan** [comment]
![image](https://github.com/node-casbin/nest-authz/assets/22289015/bfb55468-ae9d-404f-ad6f-cf3a3e854d7f)

**Comment by hsluoyz** [comment]
@wujingquan the code has been restored. Please use latest v2.6.0: https://www.npmjs.com/package/nest-authz/v/2.6.0
