### ISSUE TITLE
Unifying RBACService and ManagementService

### ISSUE THREAD

**Issue by Dallin343** [node-casbin/nest-authz#170]
Currently, `nest-authz` provides two different services to manage authorization: `AuthzRBACService` and `AuthZManagementService`. `AuthzRBACService` is intended to be a wrapper of the RBAC Casbin API, while `AuthzManagementSErvice` wraps the lower-level Management Casbin API.  

However, in `node-casbin`, the publicly exported enforcers are subclassed so that they provide the Management + RBAC API. It would be useful to have both the Management and RBAC APIs provided by one service.  

I am planning to create a PR unifying the two AuthZ services into one service which wraps the Management + RBAC APIs, possibly just called `AuthzService`. But first, I wanted to file an issue in order to open a discussion about any potential issues, design considerations, etc. if any are needed.  

Is there anything precluding a unified API being provided by a singular service?

**Comment by hsluoyz** [comment]
@Dallin343 good idea. But you should not remove the old two services to keep back compatibility. Because a lot of people are using them. You can add a third service to wrap them all

**Comment by Dallin343** [comment]
I will do that. I am moving all of the API functions into a separate file to prevent code duplication. Since this new service will cover both of the old services, I think the old services should be marked deprecated so they can be removed in a later major version release. What do you think?
