### ISSUE TITLE
Nest 10 版本的依赖也该提升了，安装的时候提示了

### ISSUE THREAD

**Issue by xuzuxing** [node-casbin/nest-authz#172]
目前的依赖还是在 9 版本的
```
 "devDependencies": {
    "@nestjs/common": "^9.0.3",
    "@nestjs/core": "^9.0.3",
    ......
  }
```

安装已经提示错误了：
`> [app build-stage 5/7] RUN npm install:
9.629 npm error code ERESOLVE
9.629 npm error ERESOLVE unable to resolve dependency tree
9.630 npm error
9.630 npm error While resolving: certeasy_nest_monorepo@1.2.0
9.630 npm error Found: reflect-metadata@0.2.2
9.630 npm error node_modules/reflect-metadata
9.630 npm error   reflect-metadata@"^0.2.0" from the root project
9.630 npm error   peer reflect-metadata@"^0.1.12 || ^0.2.0" from @nestjs/common@10.4.15
9.630 npm error   node_modules/@nestjs/common
9.630 npm error     @nestjs/common@"^10.0.0" from the root project
9.630 npm error     peer @nestjs/common@"^9.0.3 || ^10.0.0" from nest-authz@2.11.0
9.630 npm error     node_modules/nest-authz
9.630 npm error       nest-authz@"^2.11.0" from the root project
9.630 npm error     5 more (@nestjs/core, @nestjs/microservices, ...)
9.630 npm error   3 more (@nestjs/core, @nestjs/microservices, @nestjs/websockets)
9.630 npm error
9.630 npm error Could not resolve dependency:
9.630 npm error peer reflect-metadata@"^0.1.13" from nest-authz@2.11.0
9.630 npm error node_modules/nest-authz
9.630 npm error   nest-authz@"^2.11.0" from the root project
9.630 npm error
9.630 npm error Fix the upstream dependency conflict, or retry
9.630 npm error this command with --force or --legacy-peer-deps
9.630 npm error to accept an incorrect (and potentially broken) dependency resolution.
9.630 npm error
9.630 npm error
9.630 npm error For a full report see:
9.630 npm error /root/.npm/_logs/2024-12-10T08_09_44_878Z-eresolve-report.txt
9.635 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-12-10T08_09_44_878Z-debug-0.log
------`

**Comment by hsluoyz** [comment]
@nodece @Shivansh-yadav13

**Comment by xuzuxing** [comment]
刚刚网卡了，没贴好错误格式
```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: apps_demo@0.0.1
npm error Found: reflect-metadata@0.2.2
npm error node_modules/reflect-metadata
npm error   reflect-metadata@"^0.2.0" from the root project
npm error   peer reflect-metadata@"^0.1.12 || ^0.2.0" from @nestjs/common@10.4.15
npm error   node_modules/@nestjs/common
npm error     @nestjs/common@"^10.0.0" from the root project
npm error     peer @nestjs/common@"^9.0.3 || ^10.0.0" from nest-authz@2.11.0
npm error     node_modules/nest-authz
npm error       nest-authz@"^2.11.0" from the root project
npm error     5 more (@nestjs/core, @nestjs/microservices, ...)
npm error   3 more (@nestjs/core, @nestjs/microservices, @nestjs/websockets)
npm error
npm error Could not resolve dependency:
npm error peer reflect-metadata@"^0.1.13" from nest-authz@2.11.0
npm error node_modules/nest-authz
npm error   nest-authz@"^2.11.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
```

**Comment by hsluoyz** [comment]
@xuzuxing plz use English. This issue will be deleted
