### ISSUE TITLE
AuthActionVerb中的read能否精分一下

### ISSUE THREAD

**Issue by dogscar** [node-casbin/nest-authz#38]
能否将AuthActionVerb中的READ精分为查询列表和查询详情。如BROWSE/READ、 LIST/GET或者QUERY/GET 等类似的，否则要单独写一个列表资源字符串

**Comment by dreamdevil00** [comment]
查询列表可以 action: QUERY, resource: list, possession: any
查询详情可以 action: QUERY, resource: details, possession: any

不知道这是否符合你的需求。 
目前的设计是的确需要维护一个资源列表。

**Comment by dogscar** [comment]
export enum Resource {
  USER = 'user',
  USER_LIST = 'user_list',

  ARTICLE = 'article',
  ARTICLE_LIST = 'article_list',

  GROUP = 'group',
  GROUP_LIST = 'group_list',
  ...
}
每个都要多定义一个list,单纯用来查询。
https://www.adaltas.com/en/2019/08/07/users-rbac-kubernetes/
https://guides.sonatype.com/repo3/technical-guides/role-based-access-controls/

**Comment by dreamdevil00** [comment]
如果细分action, 为了满足用户对action灵活的需求， 可能需要用户自己提供action的值， 而不是目前通用的CRUD。 这会造成破坏性更新，会发布在v2中。

**Comment by dogscar** [comment]
@dreamdevil00   嗯，其实还有很多action, 如import、export，所以这个action最好还是让用户自己提供

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@dreamdevil00 这个issue在开发中吗，我应该可以接手

**Comment by dreamdevil00** [comment]
@Zxilly 没有，非常欢迎PR

**Comment by dzcpy** [comment]
有人在做了吗？

**Comment by Zxilly** [comment]
@dzcpy 我暂时在忙别的

**Comment by hsluoyz** [comment]
Any contribution for this PR is welcome!

**Comment by wiatrM** [comment]
Can we chat in english?

**Comment by hsluoyz** [comment]
@dreamdevil00 hi, given Casbin is an international open-source project involving developers from all over the world. And this middleware is one part of Casbin's ecosystem. Can we use English everywhere including the issues for better experiences for global developers?

**Comment by hsluoyz** [comment]
@dreamdevil00 BTW, I saw that a lot of recent issues and PRs are not processed (including this one from 2 years ago).

So are you willing to contribute this project to the Node-Casbin community and let the community help maintain it together with you? At the same time, you will also become a Node-Casbin community member.

**Comment by dreamdevil00** [comment]
> @dreamdevil00 BTW, I saw that a lot of recent issues and PRs are not processed (including this one from 2 years ago).
> 
> So are you willing to contribute this project to the Node-Casbin community and let the community help maintain it together with you? At the same time, you will also become a Node-Casbin community member.

Yes.  It would be a better choice. How to do that? @hsluoyz

**Comment by hsluoyz** [comment]
@dreamdevil00 thanks! Already invited:

![image](https://user-images.githubusercontent.com/3787410/128673398-a4214766-ab04-4ebb-be78-4eccfdcabe2e.png)

Then plz go to settings, click Transfer to transfer it to `node-casbin`:

![image](https://user-images.githubusercontent.com/3787410/128673337-d58bd935-71e5-456d-a73f-8237bba612de.png)

**Comment by dreamdevil00** [comment]
But there's already a nest-authz exists, so transfer failed. Any help? @hsluoyz

**Comment by hsluoyz** [comment]
@dreamdevil00 plz try again.

**Comment by hsluoyz** [comment]
@dreamdevil00 saw it :) Can you also join our npmjs org `casbin` and add the NPM package to the org?

![image](https://user-images.githubusercontent.com/3787410/128674923-41ca3c19-e658-43d0-9ffe-ff7ee9a6b79d.png)

Then add the pkg at: https://www.npmjs.com/settings/casbin/packages

![image](https://user-images.githubusercontent.com/3787410/128675011-4633e4ce-6c24-4c1c-b22d-c31553be91f9.png)

**Comment by dreamdevil00** [comment]
But there's no `Add pakcage`,
Anything wrong?

**Comment by hsluoyz** [comment]
@dreamdevil00 then go to: https://www.npmjs.com/settings/casbin/teams/team/core/access , click:

![image](https://user-images.githubusercontent.com/3787410/128676412-2a51e8ad-b197-47df-8e27-7e9fac4137bd.png)

**Comment by dreamdevil00** [comment]
![image](https://user-images.githubusercontent.com/16096871/128676762-4ca0ae72-cd2a-44bc-b316-de15081da344.png)
It seems that I have no permission to do that.

**Comment by hsluoyz** [comment]
@dreamdevil00 try again

**Comment by dreamdevil00** [comment]
![image](https://user-images.githubusercontent.com/16096871/128677168-2ede749e-b35e-4cdb-b81d-739cacd5546c.png)
Add to authz failed due to lack permission

**Comment by hsluoyz** [comment]
@dreamdevil00 I think it already works: https://www.npmjs.com/settings/casbin/packages

![image](https://user-images.githubusercontent.com/3787410/128677394-67f7e461-6516-46a2-a9c8-fa1204b9baa0.png)

Thanks!

**Comment by dreamdevil00** [comment]
It seems works. Thank you for your help!

**Comment by hsluoyz** [comment]
@Zxilly plz work on this issue
